USE kolkata_restaurant_db;
 
--  top 10 total spending of each customer?
select 
c.customer_id,
c.customer_name,
round(sum(o.total_bill),2) as Total_spent
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id, c.customer_name
order by Total_spent  desc
limit 10;

--  top 10 How much revenue has each employee generated?
select 
e.employee_id,
e.employee_name,
round(sum(o.total_bill),2) as revenue
from employees e
join orders o
on e.employee_id = o.employee_id	
group by e.employee_id,e.employee_name
order by revenue desc
limit 10;

-- How many orders has each employee handled?
Select 
e.employee_id,e.employee_name,
count(o.order_id) as total_orders
from employees e
join orders o
on e.employee_id = o.employee_id
group by e.employee_id,e.employee_name
order by total_orders desc;

-- What is the total revenue generated by each menu category?
select 
mc.category_name,
round(sum(od.amount),2) as revenue
from menu_categories mc
join menu_items mi
on mc.category_id= mi.category_id
join order_details od
on mi.item_id = od.item_id
group by mc.category_name
order by revenue desc ;

-- What are the Top 10 best-selling menu items?
select mi.item_id,
mi.item_name,
count(od.quantity) as quantity_sold
from menu_items mi
join order_details od 
on mi.item_id= od.item_id
group by mi.item_id,mi.item_name
order by quantity_sold desc 
limit 10;

-- Which menu items are sold the least?
select mi.item_id,
mi.item_name,
count(od.quantity) as quantity_sold
from menu_items mi
join order_details od 
on mi.item_id= od.item_id
group by mi.item_id,mi.item_name
order by quantity_sold asc 
limit 10;
-- revenue by month 
SELECT
    MONTH(order_date) AS month,
    ROUND(SUM(total_bill),2) AS revenue
FROM orders
GROUP BY MONTH(order_date)
ORDER BY month;

-- daily revenue of resurent 
select
order_date as date,
round(sum(total_bill),2) as revenue
from orders
group by date
order by revenue desc;

-- How much revenue was received through each payment mode?
select payments.payment_mode,
round(sum(payments.amount),2) as total_payment
from payments
group by payment_mode
order by total_payment desc;

-- Which orders have a value greater than the average order value?
select *
from orders
where total_bill > 
(select avg(orders.total_bill)
from orders)
;

SELECT
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING COUNT(o.order_id) > 5;

-- Which inventory items are below the reorder level?
SELECT
    ingredient_name,
    current_stock,
    reorder_level
FROM inventory
WHERE current_stock < reorder_level;

-- How many ingredients does each supplier provide?
SELECT
    s.supplier_name,
    COUNT(i.ingredient_id) AS total_ingredients
FROM suppliers s
JOIN inventory i
ON s.supplier_id = i.supplier_id
GROUP BY s.supplier_name
ORDER BY total_ingredients DESC;

-- What is the total revenue for each order type?
SELECT
    order_type,
    ROUND(SUM(total_bill),2) AS revenue
FROM orders
GROUP BY order_type;

-- What is the revenue generated from Veg and Non Veg menu items?
SELECT
    mi.food_type,
    ROUND(SUM(od.amount),2) AS revenue
FROM menu_items mi
JOIN order_details od
ON mi.item_id = od.item_id
GROUP BY mi.food_type
order by revenue desc;
-- Which top 3  menu category generates the highest revenue?
SELECT
    mc.category_name,
    ROUND(SUM(od.amount),2) AS revenue
FROM menu_categories mc
JOIN menu_items mi
ON mc.category_id = mi.category_id
JOIN order_details od
ON mi.item_id = od.item_id
GROUP BY mc.category_name
ORDER BY revenue DESC
LIMIT 3;

-- What is the average selling price of menu items in each category?
SELECT
    mc.category_name,
    ROUND(AVG(mi.selling_price),2) AS avg_price
FROM menu_categories mc
JOIN menu_items mi
ON mc.category_id = mi.category_id
GROUP BY mc.category_name
order by avg_price desc;

-- Classify customers as Premium, Gold, or Regular based on their total spending.
SELECT
    c.customer_name,
    SUM(o.total_bill) AS total_spent,
    CASE
        WHEN SUM(o.total_bill) >= 10000 THEN 'Premium'
        WHEN SUM(o.total_bill) >= 5000 THEN 'Gold'
        ELSE 'Regular'
    END AS customer_type
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC;